### ISSUE TITLE
Clic en dehors d'une fenêtre modale

### ISSUE THREAD

**Issue by LarcM7** [MTESSDev/utd-webcomponents#35]
[gif](https://github.com/MTESSDev/utd-webcomponents/blob/main/test/images/clicDehors.gif)

Relâcher le bouton de la souris en dehors de la fenêtre modale ferme la fenêtre modale. Même si le clic avait commencé à l'intérieur de la fenêtre

**Comment by loima02** [comment]
C'est en PROD
