### ISSUE TITLE
Un bouton de modale désactivé suite à un déclenchement par la touche "ENTER" n'est pas bloqué

### ISSUE THREAD

**Issue by anisite** [MTESSDev/utd-webcomponents#4]
1. ouvrir une modale de UTD
2. se rendre sur le bouton action avec le clavier
3. faire "enter" très très rapidement
4. l'évèvement s'exécute autant de fois que de pression sur enter
    a. ce n'est pas possible de le reproduire avec le clique de souris

**Comment by anisite** [comment]
Est-ce qu'on peut fermer ?

**Comment by j0ber** [comment]
c'est corrigé en v1.6.1. Je dois la publier.

**Comment by j0ber** [comment]
Corrigé version 1.6.1.
