### ISSUE TITLE
Composant "champs date" - Améliorer ergonomie afficher icone quand le champs est desactiver

### ISSUE THREAD

**Issue by linkprada** [MTESSDev/utd-webcomponents#57]
invistiguer la possibiliter d'afficher l'icone (calandrier) lors de la desactivation du champ (utilisation de l'attribut "disabled")

repro
`<input type="date" id="champ3" class="utd-form-control" disabled>`

![demo](https://github.com/MTESSDev/utd-webcomponents/assets/54531034/8686baa8-6268-41d7-9833-1a3f5b8b7f2f)

**Comment by j0ber** [comment]
Bonjour,

C'est un comportement natif du champ date de retirer le calendrier lorsque le champ est désactivé ou en lecture seule.
Nous ne modifierons pas ce comportement.

Par contre ce qui n'est pas normal c'est d'avoir un champ désactivé. Normalement on ne désactive jamais un champ dans une interface, SAUF s'il s'agit d'un champ qui est TOUJOURS affiché en lecture seule, ce qui n'est pas votre cas.

Tel que discuté et convenu avec Julie Le de l'équipe UI/UX, vous devriez retirer le disabled sur le champ date et ajuster vos validations en conséquence. Cela respecte les bonnes pratiques.
