### ISSUE TITLE
L’espacement entre la signature et le nom du Ministère doit être environ 3 drapeaux, dans utd l’espace n’est pas respecté

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/utd-webcomponents#59]
Problème rapporté par le MLF..

![image](https://github.com/MTESSDev/utd-webcomponents/assets/43148349/72f8949a-0051-4156-ab41-5e4c3a2e4d05)

**Comment by j0ber** [comment]
C'est tout à fait vrai. C'est d'ailleurs un changement prévu dans la version 2.1.0 de UTD qui est actuellement en cours de développement et qui devrait être disponible sous peu.

Dans cette nouvelle version, le composant PIV entête a été ajusté afin de respecter les spécifications officiellement diffusées dans le système de design gouvernemental en novembre 2023 et ajustées le 30 janvier dernier.

**Comment by drogu02** [comment]
Ok parfait merci!

**Comment by j0ber** [comment]
Livré avec la version 2.1.0 le 2024-03-05
