### ISSUE TITLE
Avoir un moyen de bloquer le copier coller et l'auto complétion dans un champs

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/utd-webcomponents#61]
Dans certaine situation, on a besoin de s'assurer que l'utilisateur a tapé lui même le texte. Par exemple pour valider son adresse courriel.

Il serait utile que dans UTD il y ait une classe ou une autre façon de bloquer le copier collé et l'auto complétion dans un champs pour forcer l'utilisateur à taper lui même un texte.

De plus, l'avoir dans UTD permettrait de l'utiliser aussi dans FRW.

Merci

**Comment by j0ber** [comment]
C'est dans la version [3.0.0](https://github.com/MTESSDev/utd-webcomponents/releases/tag/3.0.0)
