### ISSUE TITLE
Problème d'affichage pour une écran à 1444px

### ISSUE THREAD

**Issue by drogu02** [MTESSDev/utd-webcomponents#67]
Problème d'affichage pour une largeur d'environ 1444px sur tous les navigateurs

Le menu plus ne devrait pas apparaitre, en plus il y a seulement la maison dans le menu principal ainsi que le bouton Connexion.
https://www.zoneentreprise.gouv.qc.ca/

![image](https://github.com/MTESSDev/utd-webcomponents/assets/43148349/04e3b069-1030-4cfa-9ce6-0ad0acd1871f)

![image](https://github.com/MTESSDev/utd-webcomponents/assets/43148349/6333af5d-3411-4502-8597-ecb39d28a836)

**Comment by j0ber** [comment]
Ok c'est bizarre car ça fonctionne très bien (voir ici https://lively-cliff-018a9540f.azurestaticapps.net/composants/navigation/menuhorizontal) autour de 1444px.

On devra se parler et que je le vois live, il y a peut-être quelque chose avec votre code ou votre css... ou réellement un problème avec UTD.

**Comment by drogu02** [comment]
On avait un problème de notre côté finalement! C'est réglé!
