### ISSUE TITLE
Ajout des icônes "Liste de vérification" et "Signature"

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/utd-webcomponents#68]
Bonjour

Est-ce qu'il serait possible d'ajouter les icônes "Liste de vérification" et "Signature" SVP

![image](https://github.com/MTESSDev/utd-webcomponents/assets/112179879/17cabd43-5a50-4bd0-b328-88150ecdef27)
![image](https://github.com/MTESSDev/utd-webcomponents/assets/112179879/4dfdd6d0-e478-438f-8bf2-1310a60e77a1)

**Comment by j0ber** [comment]
Je ne crois pas voir ces icônes dans les icônes normalisées : https://linearicons.com/premium/preview

Y en a t-il d'autres qui pourraient être utilisées dans cette banque?

**Comment by jpbeaulieu1** [comment]
Bonjour
Je vais utiliser "document" et "papier-crayon". Je vais aviser la DCOM qu'il ne peuvent utiliser que les icones normalisées.

Merci
