### ISSUE TITLE
path-courant ne semble pas disponible dans utd-menu-vertical

### ISSUE THREAD

**Issue by jpbeaulieu1** [MTESSDev/utd-webcomponents#74]
Bonjour

La propriété path-courant ne semble pas disponible dans utd-menu-vertical? J'utilise Blazor web app (SPA). J'ai une page de pilotage générique qui permet la mise à jour de différents domaines de valeur. Le click sur sur un item change la route de la page mais ne "navigue" pas. Le menu vertical ne prend pas en compte le changement de route. Si j'accède de directement à l'URL le menu ne reconnait pas non plus la route et n'indique pas l'item courent.

On peut faire sans l'item actif aussi.

Merci

![image](https://github.com/user-attachments/assets/013e804a-34f4-41f0-aec5-4b50f545e0f4)

**Comment by j0ber** [comment]
Bonjour,
Il me faudrait ton html (le bloc de code qui contient le utd-menu-vertical et les utd-menu-vertical-item).

Il n'y a pas de path-courant dans le menu vertical. 

L'élément actif est déterminé automatiquement à partir de l'url de la page et de l'attribut "href" de l'élément "utd-menu-vertical-item".

Comme tu es dans une SPA je suis curieux de savoir à quoi ressemble la définition de ton menu.

Merci!
