### ISSUE TITLE
Champ de formulaire textarea - Ajouter un compteur de caractères + hauteur automatique

### ISSUE THREAD

**Issue by j0ber** [MTESSDev/utd-webcomponents#86]
Exemple :  

![image](https://github.com/user-attachments/assets/e736764c-7199-41c3-ba51-6a87fd000c54)

**Comment by andbois** [comment]
Le calcul du nombre de caractère est un besoin prioritaire :) pour notre développement en cours

**Comment by j0ber** [comment]
Version 3.1.0
